app:
  jwt:
    secret-key: 123

server:
  port: 8000

spring:
  jpa:
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        order_inserts: true
        order_updates: true
        jdbc.batch_size: 10000
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/2312_course_db
    username: root
    password: dreamy
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      pool-name: course_db_cp
      maximum-pool-size: 5
      jdbc-url: ${spring.datasource.url}
      username: ${spring.datasource.username}
      password: ${spring.datasource.password}
      driver-class-name: ${spring.datasource.driver-class-name}
      connection-init-sql: SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;
      data-source-properties:
        useUnicode: true
        characterEncoding: UTF-8
        rewriteBatchedInserts: true
        rewriteBatchedStatements: true

springdoc:
  api-docs:
    path: /api-docs
  paths-to-match:
    - /api/**
    - /login
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    doc-expansion: none
    display-request-duration: true
    disable-swagger-default-url: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

logging:
  level:
    org.hibernate.SQL: debug