package com.demo.global.common.exception.enums;

import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor(access = AccessLevel.PRIVATE)
public enum ApiExceptionType {

    /* 기타 */
    COMMON("-100", ""),
    COMMON_CONTENT_TYPE_NOT_VALID("-111", ""),
    COMMON_CONTENT_TYPE_NOT_SUPPORTED("-112", ""),
    COMMON_JSON_MAPPING_FAILED("-120", ""),
    COMMON_JSON_PROCESSING_FAILED("-121", ""),
    COMMON_QUERY_RESULT_NOT_VALID("-130", ""),
    COMMON_QUERY_SCRIPT_NOT_VALID("-131", ""),
    COMMON_QUERY_SCRIPT_NOT_SUPPORTED("-132", ""),
    COMMON_SOCKET_MESSAGE_SENDING_FAILED("-140", ""),
    COMMON_SOCKET_MESSAGE_RECEIVING_FAILED("-141", ""),

    /* 사용자 관련 */
    USER_EXISTED("-200", ""),
    USER_NOT_EXISTED("-201", ""),
    USER_AUTHENTICATION_FAILED("-210", ""),
    USER_AUTHORIZATION_NOT_VALID("-211", ""),
    USER_AUTHENTICATION_NOT_VALID("-212", ""),
    USER_AUTHENTICATION_TOKEN_NOT_VALID("-213", ""),

    /* 대학, 학부, 학과 관련 */
    COLLEGE_EXISTED("-300", ""),
    COLLEGE_NOT_EXISTED("-301", ""),
    COLLEGE_DIVISION_EXISTED("-310", ""),
    COLLEGE_DIVISION_NOT_EXISTED("-311", ""),
    COLLEGE_DEPARTMENT_EXISTED("-320", ""),
    COLLEGE_DEPARTMENT_NOT_EXISTED("-321", ""),
    COLLEGE_COURSE_EXISTED("-330", ""),
    COLLEGE_COURSE_NOT_EXISTED("-331", ""),
    COURSE_EXISTED("-340", ""),
    COURSE_NOT_EXISTED("-341", ""),

    /* 수강 신청 관련 */
    COURSE_REGISTRATION_DUPLICATED("-400", ""),
    COURSE_REGISTRATION_NOT_EXISTED("-401", ""),
    COURSE_REGISTRATION_COURSE_DUPLICATED("-402", ""),
    COURSE_REGISTRATION_COURSE_TIMETABLE_DUPLICATED("-403", ""),
    COURSE_REGISTRATION_COUNT_NOT_VALID("-404", ""),
    COURSE_REGISTRATION_CART_NOT_EXISTED("-410", ""),
    COURSE_REGISTRATION_CART_DUPLICATED("-411", ""),
    COURSE_REGISTRATION_CART_COUNT_NOT_VALID("-412", ""),
    COURSE_REGISTRATION_CREDIT_NOT_VALID("-420", ""),
    COURSE_REGISTRATION_CREDIT_LEFT_NOT_VALID("-421", ""),

    /* 강의 검색 관련 */
    COURSE_SEARCH_COURSE_YEAR_NOT_VALID("-500", ""),
    COURSE_SEARCH_COURSE_SEMESTER_NOT_VALID("-501", ""),
    COURSE_SEARCH_COURSE_TYPE_NOT_VALID("-502", ""),
    ;

    private final String code;
    private final String message;
}